### Fancy Indexing in Numpy


In [1]:
import numpy as np
v = np.arange(0, 30, 3)


In [2]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
v[1:6:2]

array([ 3,  9, 15])

In [4]:
retrieve = [1, 3, 5]

In [5]:
v[retrieve]

array([ 3,  9, 15])

#### Fancy in multi dimensions

In [6]:
m = np.arange(9).reshape((3,3))

In [7]:
row = np.array([0,1])
col = np.array([1,2])

In [10]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
m[row, col] # Retrive 1strow 2nd item first then 2nd row 3rd item.

array([1, 5])

In [9]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])