### Random Acsessing in Numpy


In [1]:
import numpy as np 

In [2]:
a = np.random.randint(10, size = (2, 3))

In [3]:
a

array([[5, 1, 3],
       [7, 0, 8]])

In [4]:
a[0]

array([5, 1, 3])

In [5]:
a[0][1]

1

### Array Slicing

In [6]:
a = np.arange(20, 30)

In [7]:
a[0:3]

array([20, 21, 22])

#### Multi dim slicing

In [8]:
m = np.random.randint(10, size = (5,5))

In [9]:
m[:, 0]

array([6, 6, 2, 4, 6])

In [10]:
m[2:5,1:3]

array([[8, 9],
       [1, 3],
       [6, 5]])

In [11]:
m

array([[6, 2, 4, 6, 9],
       [6, 0, 9, 7, 9],
       [2, 8, 9, 6, 9],
       [4, 1, 3, 2, 1],
       [6, 6, 5, 2, 1]])