### Numpy Features



In [10]:
import numpy as np

In [11]:
a = np.random.random_integers(10, size = 10,)

C:\Users\gulse\AppData\Local\Temp\ipykernel_19436\1759167926.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  a = np.random.random_integers(10, size = 10,)


In [12]:
a.ndim

1

In [13]:
a.shape

(10,)

In [14]:
a.dtype

dtype('int32')

In [15]:
b = np.random.random_integers(10, size=(2, 5))

C:\Users\gulse\AppData\Local\Temp\ipykernel_19436\1902270358.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  b = np.random.random_integers(10, size=(2, 5))


In [16]:
b

array([[6, 2, 4, 8, 4],
       [5, 2, 9, 3, 6]])

In [17]:
b.shape

(2, 5)

In [18]:
b.ndim

2

In [19]:
b.dtype

dtype('int32')

### Numpy Reshaping

In [20]:
b

array([[6, 2, 4, 8, 4],
       [5, 2, 9, 3, 6]])

In [33]:
c = b.reshape((5, 2), order="A")

In [34]:
c

array([[6, 2],
       [4, 8],
       [4, 5],
       [2, 9],
       [3, 6]])