### Operations with SubArrays


In [32]:
import numpy as np

a = np.random.randint(10, size = (5, 5))


In [33]:
a

array([[0, 3, 9, 5, 6],
       [0, 3, 0, 0, 9],
       [9, 0, 3, 6, 2],
       [3, 7, 3, 4, 4],
       [8, 2, 7, 5, 8]])

In [34]:
b = a[:,2].copy()

In [35]:
b[0] = 2
b[1] = 3

In [36]:
b

array([2, 3, 3, 3, 7])

In [37]:
a

array([[0, 3, 9, 5, 6],
       [0, 3, 0, 0, 9],
       [9, 0, 3, 6, 2],
       [3, 7, 3, 4, 4],
       [8, 2, 7, 5, 8]])