### Conditional Operations

In [2]:
import numpy as np
v = np.arange(1, 6)

In [3]:
v

array([1, 2, 3, 4, 5])

In [4]:
v > 5

array([False, False, False, False, False])

In [5]:
v[v > 3] # Like that.

array([4, 5])

### Math Operations

In [6]:
v + 2

array([3, 4, 5, 6, 7])

In [7]:
v - 2

array([-1,  0,  1,  2,  3])

In [8]:
v * 2

array([ 2,  4,  6,  8, 10])

In [9]:
v / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [11]:
v[v % 2 == 0]

array([2, 4])

In [13]:
#ufunc, functions is worked while math operaiton. 

np.absolute(np.array([-3, -4, -5]))

array([3, 4, 5])

Calculate 

5*x^0 + x^1  = 12

x^0 + 3 * x^1 = 10

In [15]:
my_matrix = np.matrix([[5, 1],
                       [1, 3]])

In [17]:
my_matrix

matrix([[5, 1],
        [1, 3]])

In [19]:
my_results = np.matrix([[12],
                        [10]])

In [20]:
x = np.linalg.solve(my_matrix, my_results)

In [21]:
x

matrix([[1.85714286],
        [2.71428571]])