In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [3]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
z = np.array([7, 8 ,9])

In [5]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 7, 8, 9])

In [6]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])

In [7]:
np.concatenate([[x, y]], axis = 0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.concatenate([a, a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
np.concatenate([a, a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Array Spliting

In [9]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [10]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [18]:
np.split(x, [2, 5])

[array([1, 2]), array([ 3, 99, 99]), array([3, 2, 1])]

In [12]:
y = np.arange(16).reshape(4,4)

In [28]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
np.vsplit(y, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [27]:
np.hsplit(y, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [15]:
np.sort(x, kind="mergesort",)

array([ 1,  1,  2,  2,  3,  3, 99, 99])