# Creating numpy arrays?


In [1]:
import numpy as np #Importing Numpy

In [2]:
a = np.array([1, 2, 3, 4]) #Assigning a to ndarray.
b = np.array([2, 3, 4, 5])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a) # -> numpy.ndarray

numpy.ndarray

In [5]:
np.array([1, 2, 3, 4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.arange(0,30, 3) #Not including 30.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [9]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10, 4, (3,4))

array([[14.26516431, 13.98448268,  4.57762923, 10.76846109],
       [ 8.80087444, 10.87433849,  6.67117723, 11.37686488],
       [12.37800543, 13.21171125,  7.35937423, 11.37514148]])

In [11]:
np.random.random_integers(0, 10, (3,4)) # Including 10.

C:\Users\gulse\AppData\Local\Temp\ipykernel_10736\2013324169.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  np.random.random_integers(0, 10, (3,4))


array([[ 3,  4,  4,  6],
       [ 7,  7,  8,  4],
       [10,  6,  9,  0]])